version: "3.9"

services:
  gollum:
    container_name: gollum
    image: gollumwiki/gollum:master
    restart: always
    ports:
      - "7654:4567/tcp"
    volumes:
      - ${PWD}/config.rb:/etc/gollum/config.rb
      - ${PWD}/gitconfig:/home/www-data/.gitconfig
      - ${PWD}/wikidata:/wiki
    command:
      - "--config=/etc/gollum/config.rb"
